### ISSUE TITLE
The backend fails to parse maps with input variables

### ISSUE THREAD

**Issue by 4tXJ7f** [dbtoaster/dbtoaster-backend#23]
Example:

```
[info] ---------[[ Employee52a ]]---------
[info] SQL -> M3           :   0.067
[error] Exception in thread "main" java.lang.RuntimeException: [11.24] failure: Expected ']'
[error] 
[error] DECLARE MAP COUNT(int)[A_NAME:string][]:(({A_NAME = 'SALES'} * AggSum([
[error] 
[error]                        ^
[error]     at scala.sys.package$.error(package.scala:27)
[error]     at ddbt.frontend.M3Parser$.apply(Parsers.scala:124)
[error]     at ddbt.frontend.M3Parser$.apply(Parsers.scala:76)
[error]     at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error]     at ddbt.Compiler$.compile(Compiler.scala:113)
[error]     at ddbt.UnitTest$$anonfun$genQuery$1.apply$mcV$sp(UnitTest.scala:219)
[error]     at ddbt.UnitTest$Printer.run(UnitTest.scala:327)
[error]     at ddbt.UnitTest$.genQuery(UnitTest.scala:219)
[error]     at ddbt.UnitTest$$anonfun$main$4$$anonfun$apply$8.apply(UnitTest.scala:146)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:143)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:129)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
[error]     at ddbt.UnitTest$.main(UnitTest.scala:129)
[error]     at ddbt.UnitTest.main(UnitTest.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) Nonzero exit code returned from runner: 1
[error] Total time: 94 s, completed Apr 24, 2014 7:57:05 AM
```

**Comment by losmi83** [comment]
The new backend indeed doesn't support maps with input variables. The Axfinder and Vwap queries from the finance dataset used to profit from using input variables.
