### ISSUE TITLE
Query files with multiple queries cannot be verified

### ISSUE THREAD

**Issue by 4tXJ7f** [dbtoaster/dbtoaster-backend#45]
The issue is that the old frontend did not distinguish between multiple queries and multiple toplevel aggregate targets. Because of that the reference result files do not make this distinction either. The new frontend on the other hand treats them differently. We have to update the reference result to make this distinction.

Example:

```
[info] ---------[[ Inequalityselfjoin ]]---------
[info] Scala codegen       :   0.516                                         
[error] Exception in thread "main" java.util.NoSuchElementException: key not found: QUERY_1_COUNT_QUERY_2_COUNT
[error]     at scala.collection.MapLike$class.default(MapLike.scala:228)
[error]     at scala.collection.AbstractMap.default(Map.scala:58)
[error]     at scala.collection.MapLike$class.apply(MapLike.scala:141)
[error]     at scala.collection.AbstractMap.apply(Map.scala:58)
[error]     at ddbt.UnitTest$$anonfun$10$$anonfun$apply$9.apply(UnitTest.scala:203)
[error]     at ddbt.UnitTest$$anonfun$10$$anonfun$apply$9.apply(UnitTest.scala:202)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[error]     at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
[error]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[error]     at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[error]     at ddbt.UnitTest$$anonfun$10.apply(UnitTest.scala:202)
[error]     at ddbt.UnitTest$$anonfun$10.apply(UnitTest.scala:200)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[error]     at scala.collection.MapLike$FilteredKeys$$anonfun$foreach$1.apply(MapLike.scala:231)
[error]     at scala.collection.MapLike$FilteredKeys$$anonfun$foreach$1.apply(MapLike.scala:231)
[error]     at scala.collection.MapLike$FilteredKeys$$anonfun$foreach$1.apply(MapLike.scala:231)
[error]     at scala.collection.MapLike$FilteredKeys$$anonfun$foreach$1.apply(MapLike.scala:231)
[error]     at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
[error]     at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:231)
[error]     at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:231)
[error]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[error]     at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[error]     at ddbt.UnitTest$.spec$1(UnitTest.scala:200)
[error]     at ddbt.UnitTest$.ddbt$UnitTest$$post$1(UnitTest.scala:225)
[error]     at ddbt.UnitTest$$anonfun$genQueryScala$1$$anonfun$apply$mcV$sp$5.apply(UnitTest.scala:237)
[error]     at ddbt.UnitTest$$anonfun$genQueryScala$1$$anonfun$apply$mcV$sp$5.apply(UnitTest.scala:237)
[error]     at ddbt.Compiler$.compile(Compiler.scala:156)
[error]     at ddbt.UnitTest$$anonfun$genQueryScala$1.apply$mcV$sp(UnitTest.scala:237)
[error]     at ddbt.UnitTest$Printer.run(UnitTest.scala:397)
[error]     at ddbt.UnitTest$.genQueryScala(UnitTest.scala:237)
[error]     at ddbt.UnitTest$$anonfun$main$4$$anonfun$apply$8.apply(UnitTest.scala:148)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:145)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:131)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
[error]     at ddbt.UnitTest$.main(UnitTest.scala:131)
[error]     at ddbt.UnitTest.main(UnitTest.scala)
```

**Comment by losmi83** [comment]
no input file to verify this issue + alpha6 abandoned
