### ISSUE TITLE
TypeChecker cannot find key (Rbtimesa)

### ISSUE THREAD

**Issue by 4tXJ7f** [dbtoaster/dbtoaster-backend#47]
```
[info] ---------[[ Rbtimesa ]]---------
[error] Exception in thread "main" java.util.NoSuchElementException: key not found: R
[error]     at scala.collection.MapLike$class.default(MapLike.scala:228)
[error]     at scala.collection.AbstractMap.default(Map.scala:58)
[error]     at scala.collection.MapLike$class.apply(MapLike.scala:141)
[error]     at scala.collection.AbstractMap.apply(Map.scala:58)
[error]     at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$ie$1(TypeCheck.scala:131)
[error]     at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$ie$1(TypeCheck.scala:116)
[error]     at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$ie$1(TypeCheck.scala:128)
[error]     at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$ie$1(TypeCheck.scala:116)
[error]     at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$ie$1(TypeCheck.scala:118)
[error]     at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$ie$1(TypeCheck.scala:116)
[error]     at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$ie$1(TypeCheck.scala:118)
[error]     at ddbt.frontend.TypeCheck$.ddbt$frontend$TypeCheck$$ist$1(TypeCheck.scala:142)
[error]     at ddbt.frontend.TypeCheck$.typeCheck(TypeCheck.scala:143)
[error]     at ddbt.frontend.TypeCheck$$anonfun$27.apply(TypeCheck.scala:157)
[error]     at ddbt.frontend.TypeCheck$$anonfun$27.apply(TypeCheck.scala:157)
[error]     at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error]     at ddbt.frontend.TypeCheck$.apply(TypeCheck.scala:158)
[error]     at ddbt.frontend.TypeCheck$.apply(TypeCheck.scala:9)
[error]     at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error]     at ddbt.Compiler$.compile(Compiler.scala:128)
[error]     at ddbt.UnitTest$$anonfun$genQueryScala$1.apply$mcV$sp(UnitTest.scala:237)
[error]     at ddbt.UnitTest$Printer.run(UnitTest.scala:397)
[error]     at ddbt.UnitTest$.genQueryScala(UnitTest.scala:237)
[error]     at ddbt.UnitTest$$anonfun$main$4$$anonfun$apply$8.apply(UnitTest.scala:148)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:145)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:131)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
[error]     at ddbt.UnitTest$.main(UnitTest.scala:131)
[error]     at ddbt.UnitTest.main(UnitTest.scala)
```

**Comment by losmi83** [comment]
the issue doesn't appear anymore
