### ISSUE TITLE
Can't check result of Runion

### ISSUE THREAD

**Issue by 4tXJ7f** [dbtoaster/dbtoaster-backend#51]
```
[error] target/tmp/Runion.scala:21: error: type mismatch;
[error]  found   : (Long, Long)
[error]  required: Long
[error]         diff(res(0).asInstanceOf[Map[Long,List[Any]]], Map[Long,List[Any]](((4L,9L),List[Any](1L)),((5L,8L),List[Any](1L)),((3L,4L),List[Any](1L)),((5L,9L),List[Any](1L)),((1L,3L),List[Any](1L)),((2L,8L),List[Any](1L)),((2L,7L),List[Any](1L)),((3L,10L),List[Any](1L)),((4L,3L),List[Any](1L)),((1L,2L),List[Any](1L))))
[error]                                                                             ^
[info] Scala compile       :   0.392                                         
[error] java.lang.ClassNotFoundException: ddbt.test.gen.Runion
[error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[error]     at java.security.AccessController.doPrivileged(Native Method)
[error]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[error]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[error]     at java.lang.Class.forName0(Native Method)
[error]     at java.lang.Class.forName(Class.java:270)
[error]     at ddbt.Utils$CPLoader.loadClass(Utils.scala:122)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[error]     at ddbt.Utils$.runMain(Utils.scala:114)
[error]     at ddbt.Utils$.scalaExec(Utils.scala:70)
[error]     at ddbt.Compiler$.compile(Compiler.scala:176)
[error]     at ddbt.UnitTest$$anonfun$genQueryScala$1.apply$mcV$sp(UnitTest.scala:242)
[error]     at ddbt.UnitTest$Printer.run(UnitTest.scala:402)
[error]     at ddbt.UnitTest$.genQueryScala(UnitTest.scala:242)
[error]     at ddbt.UnitTest$$anonfun$main$4$$anonfun$apply$8.apply(UnitTest.scala:149)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:146)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:131)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
[error]     at ddbt.UnitTest$.main(UnitTest.scala:131)
[error]     at ddbt.UnitTest.main(UnitTest.scala)
```

**Comment by losmi83** [comment]
Doesn't appear anymore
