### ISSUE TITLE
Tuple24 does not exist in Scala

### ISSUE THREAD

**Issue by 4tXJ7f** [dbtoaster/dbtoaster-backend#57]
```
[info] ---------[[ Tpch17a ]]---------
[info] SQL -> M3           :   0.396
[info] Scala codegen       :   0.189                                         
[error] target/tmp/Tpch17a.scala:41: error: type Tuple24 is not a member of package scala
[error]   val QUERY17_mLINEITEM16 = M3Map.make[(Long,String,String,String,String,Long,String,Double,String,Long,Long,Long,Double,Double,Double,Double,String,String,Date,Date,Date,String,String,String),Double]((k:(Long,String,String,String,String,Long,String,Double,String,Long,Long,Long,Double,Double,Double,Double,String,String,Date,Date,Date,String,String,String))=>k._1);
[error]                                        ^
[info] Scala compile       :   0.619                                         
[error] java.lang.ClassNotFoundException: ddbt.test.gen.Tpch17a
[error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[error]     at java.security.AccessController.doPrivileged(Native Method)
[error]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[error]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[error]     at java.lang.Class.forName0(Native Method)
[error]     at java.lang.Class.forName(Class.java:270)
[error]     at ddbt.Utils$CPLoader.loadClass(Utils.scala:122)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[error]     at ddbt.Utils$.runMain(Utils.scala:114)
[error]     at ddbt.Utils$.scalaExec(Utils.scala:70)
[error]     at ddbt.Compiler$.compile(Compiler.scala:176)
[error]     at ddbt.UnitTest$$anonfun$genQueryScala$1.apply$mcV$sp(UnitTest.scala:242)
[error]     at ddbt.UnitTest$Printer.run(UnitTest.scala:402)
[error]     at ddbt.UnitTest$.genQueryScala(UnitTest.scala:242)
[error]     at ddbt.UnitTest$$anonfun$main$4$$anonfun$apply$8.apply(UnitTest.scala:149)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:146)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:131)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
[error]         at ddbt.UnitTest$.main(UnitTest.scala:131)
[error]     at ddbt.UnitTest.main(UnitTest.scala)
```

**Comment by losmi83** [comment]
alpha6 abandoned
