### ISSUE TITLE
Scala 2.10 vs 2.11 compilation problems in binary distribution

### ISSUE THREAD

**Issue by szarnyasg** [dbtoaster/dbtoaster-backend#91]
The Linux binary distribution is bundled with Scala 2.10 (as shown by the version string `Scala 2.10.2-20140310-140650-2481f036a5`). However, it generates code that uses Scala 2.11-specific features, resulting in a `NoSuchMethodError`:

```$ bin/dbtoaster -l scala -r examples/queries/simple/r_selectstar.sql 
Java 1.8.0_161, Scala 2.10.2-20140310-140650-2481f036a5
Uncaught error from thread [DDBT-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[DDBT]
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at ddbt.gen.Dbtoaster$$anonfun$receive$1$$anonfun$applyOrElse$2.apply(dbtoaster.lYWY5t.scala:115)
	at ddbt.gen.Dbtoaster$$anonfun$receive$1$$anonfun$applyOrElse$2.apply(dbtoaster.lYWY5t.scala:115)
	at ddbt.lib.store.IdxHash.foreach(Idx.java:105)
	at ddbt.lib.store.Store$$anonfun$foreach$1.apply$mcV$sp(Store.scala:228)
	at ddbt.lib.store.Store$$anonfun$foreach$1.apply(Store.scala:228)
	at ddbt.lib.store.Store$$anonfun$foreach$1.apply(Store.scala:228)
	at ddbt.lib.store.Store.time(Store.scala:217)
	at ddbt.lib.store.Store.foreach(Store.scala:228)
	at ddbt.gen.Dbtoaster$$anonfun$receive$1.applyOrElse(dbtoaster.lYWY5t.scala:115)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

real	0m0.580s
user	0m0.968s
sys	0m0.044s
```

I spun up a new Ubuntu VM to double-check this (with Scala 2.11 installed exclusively), but it had the same issue.

**Comment by losmi83** [comment]
I got no problem with a fresh Ubuntu, Scala 2.11 and Java 1.8:

ubuntu@ip-172-30-0-242:~/dbtoaster$ scala -version
Scala code runner version 2.11.6 -- Copyright 2002-2013, LAMP/EPFL
ubuntu@ip-172-30-0-242:~/dbtoaster$ java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
ubuntu@ip-172-30-0-242:~/dbtoaster$ ll ../dbtoaster_linux_3387.tgz 
-rw-rw-r-- 1 ubuntu ubuntu 38402303 Apr 18 10:33 ../dbtoaster_linux_3387.tgz
ubuntu@ip-172-30-0-242:~/dbtoaster$ 
ubuntu@ip-172-30-0-242:~/dbtoaster$ bin/dbtoaster -l scala examples/queries/simple/rs.sql -r
Java 1.8.0_162, Scala 2.10.2-20140310-140650-2481f036a5
Time: 0.006s (20/0)
AGG1:
156
AGG2:
108
real	0m0.866s
user	0m0.800s
sys	0m0.060s

**Comment by szarnyasg** [comment]
Thanks for checking this out, I'll keep looking.

**Comment by szarnyasg** [comment]
Okay, so `rs.sql` works, but `r_selectstar.sql` doesn't.

```$ bin/dbtoaster -l scala -r examples/queries/simple/r_selectstar.sql```

I used this command to produce the exception in the original post.
